version: "3.5"

networks:

  # Explicitly defined connector network to be able to set static IPs
  connector.testnet:
    name: connector.testnet
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.1.0/24

services:

  ######################################################################
  #
  # Environment variables and arguments
  #
  # This arguments and environment variables used across containers.
  #
  # EXTERNAL_IP is server's public IP address available for other
  # nodes or clients to connect and used by daemon to announce
  # right location.
  #
  ######################################################################

  ######################################################################
  #
  # Testnet containers
  #
  # This containers intended to be run on standalone machine. You should
  # create new machine for each deploy.
  #
  ######################################################################

  connector.testnet:
    container_name: connector.testnet
    image: connector.testnet
    build:
      context: ./connector/
    environment:
        - EXCHANGE_DISABLED
    networks:
      connector.testnet:
        ipv4_address: 172.100.1.100
    volumes:
      - /connector/connector.testnet:/root/.connector
      - /connector/bitcoin-lightning.testnet:/root/.lnd/:ro
    ports:
      # RPC port
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:9002:9002"
      # Prometheus monitoring
      - "${PRIVATE_IP?PRIVATE_IP environment variable should be defined}:9999:9999"
    logging:
      driver: journald
    restart: always
    depends_on:
      - bitcoin.testnet
      - bitcoin-lightning.testnet
      - bitcoin-cash.testnet
      - dash.testnet
      - ethereum.testnet
      - litecoin.testnet

  bitcoin.testnet:
    container_name: bitcoin.testnet
    image: bitcoin.testnet
    build:
      context: ./bitcoin
      args:
        - BITCOIN_VERSION
    environment:
      - EXTERNAL_IP
    networks:
      connector.testnet:
    volumes:
      - /connector/bitcoin.testnet:/root/.bitcoin
    ports:
      # P2P port
      - "8333:8333"
    logging:
      driver: journald
    restart: always

  bitcoin-lightning.testnet:
    container_name: bitcoin-lightning.testnet
    image: bitcoin-lightning.testnet
    build:
      context: ./bitcoin-lightning
      args:
        - LND_REVISION
    environment:
      - EXTERNAL_IP
    networks:
      connector.testnet:
        ipv4_address: 172.100.1.101
    volumes:
      - /connector/bitcoin.testnet:/root/.bitcoin:ro
      - /connector/bitcoin-lightning.testnet:/root/.lnd
    ports:
      # P2P port
      - "9735:9735"
    logging:
      driver: journald
    restart: always
    depends_on:
      - bitcoin.testnet

  bitcoin-cash.testnet:
    container_name: bitcoin-cash.testnet
    image: bitcoin-cash.testnet
    build:
      context: ./bitcoin-cash
      args:
        - BITCOIN_CASH_VERSION
    environment:
      - EXTERNAL_IP
    networks:
      connector.testnet:
    volumes:
      - /connector/bitcoin-cash.testnet:/root/.bitcoin
    ports:
      # P2P port
      - "9333:9333"
    logging:
      driver: journald
    restart: always
  
  dash.testnet:
    container_name: dash.testnet
    image: dash.testnet
    build:
      context: ./dash
      args:
        - DASH_VERSION
    environment:
      - EXTERNAL_IP
    networks:
      connector.testnet:
    volumes:
      - /connector/dash.testnet:/root/.dashcore
    ports:
      # P2P port
      - "10333:10333"
    logging:
      driver: journald
    restart: always

  ethereum.testnet:
    container_name: ethereum.testnet
    image: ethereum.testnet
    build:
      context: ./ethereum
      args:
        - ETHEREUM_REVISION
    environment:
      - EXTERNAL_IP
    networks:
      connector.testnet:
    volumes:
      - /connector/ethereum.testnet:/root/.ethereum
    ports:
      # P2P port
      - "11333:11333"
    logging:
      driver: journald
    restart: always

  litecoin.testnet:
    container_name: litecoin.testnet
    image: litecoin.testnet
    build:
      context: ./litecoin
      args:
        - LITECOIN_VERSION
    environment:
      - EXTERNAL_IP
    networks:
      connector.testnet:
    volumes:
      - /connector/litecoin.testnet:/root/.litecoin
    ports:
      # P2P port
      - "12333:12333"
    logging:
      driver: journald
    restart: always